### ISSUE TITLE
Sandbox tokens in README?

### ISSUE THREAD

**Issue by jasisk** [avidas/flask-paypal-verify#1]
Hi there. Noticed you have some tokens in your readme. Are those valid? If so, they should be invalidated. If not, disregard me and have a nice day. ;)

**Comment by avidas** [comment]
Hey @jasisk thanks for creating the issue. Sorry it took so long to get back to you. I will take a look at it soon.

**Comment by avidas** [comment]
I could remove them, wonder how much help it would do at this point though https://github.com/search?q=EBWKjlELKMYqRNQ6sYvFo64FtaRLRR5BdHEESmha49TM&ref=searchresults&type=Code&utf8=%E2%9C%93 . They are really old credentials and likely to be invalidated.
